# clusters/all/gitops.yaml
apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: kluctl-demo
  namespace: kluctl-system
spec:
  interval: 1m
  source:
    git:
      url: https://github.com/herveleclerc/kluctl-demo.git
      path: demo 
  target: k8s-ims
  prune: true
  delete: true
